name: popout-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - matplotlib
  - notebook
  - ipykernel
  - pytest
  - pytest-cov
  - pip
  - pygame
  - pip:
    - -e .