"""PopOut GUI package — re-exports all public symbols for backward compatibility."""

from src.engine.standard.bitboard import COLS, ROWS
from src.interfaces.gui.assets import (
    BOARD_HEIGHT,
    BOARD_WIDTH,
    CELL_SIZE,
    HUD_BOTTOM_HEIGHT,
    HUD_TOP_HEIGHT,
    WINDOW_HEIGHT,
    WINDOW_WIDTH,
    COLOR_ACCENT,
    COLOR_ACCENT_LIGHT,
    COLOR_BG_BOTTOM,
    COLOR_BG_TOP,
    COLOR_BOARD,
    COLOR_BOARD_DARK,
    COLOR_BOARD_SHADOW,
    COLOR_EMPTY,
    COLOR_EMPTY_HOVER,
    COLOR_EMPTY_SHADOW,
    COLOR_ERROR,
    COLOR_HOVER,
    COLOR_OVERLAY,
    COLOR_P1,
    COLOR_P1_GLOW,
    COLOR_P1_HI,
    COLOR_P2,
    COLOR_P2_GLOW,
    COLOR_P2_HI,
    COLOR_PANEL,
    COLOR_PANEL_BORDER,
    COLOR_PANEL_LIGHT,
    COLOR_TEXT,
    COLOR_TEXT_MUTED,
    create_fonts,
)
from src.interfaces.gui.state import AnimationState, Difficulty, CoordinateMapper
from src.interfaces.gui.components import PauseMenu
from src.interfaces.gui.renderer import (
    _draw_board,
    _draw_disc,
    _draw_glow_circle,
    _draw_pause_menu,
    _draw_vertical_gradient,
    _player_color,
    _player_glow,
)
from src.interfaces.gui.core import _column_from_mouse, _encode_move, _make_ai_engine, launch_gui

__all__ = [
    "COLS",
    "ROWS",
    "BOARD_HEIGHT",
    "BOARD_WIDTH",
    "CELL_SIZE",
    "HUD_BOTTOM_HEIGHT",
    "HUD_TOP_HEIGHT",
    "WINDOW_HEIGHT",
    "WINDOW_WIDTH",
    "COLOR_ACCENT",
    "COLOR_ACCENT_LIGHT",
    "COLOR_BG_BOTTOM",
    "COLOR_BG_TOP",
    "COLOR_BOARD",
    "COLOR_BOARD_DARK",
    "COLOR_BOARD_SHADOW",
    "COLOR_EMPTY",
    "COLOR_EMPTY_HOVER",
    "COLOR_EMPTY_SHADOW",
    "COLOR_ERROR",
    "COLOR_HOVER",
    "COLOR_OVERLAY",
    "COLOR_P1",
    "COLOR_P1_GLOW",
    "COLOR_P1_HI",
    "COLOR_P2",
    "COLOR_P2_GLOW",
    "COLOR_P2_HI",
    "COLOR_PANEL",
    "COLOR_PANEL_BORDER",
    "COLOR_PANEL_LIGHT",
    "COLOR_TEXT",
    "COLOR_TEXT_MUTED",
    "create_fonts",
    "AnimationState",
    "Difficulty",
    "CoordinateMapper",
    "PauseMenu",
    "_draw_board",
    "_draw_disc",
    "_draw_glow_circle",
    "_draw_pause_menu",
    "_draw_vertical_gradient",
    "_player_color",
    "_player_glow",
    "_column_from_mouse",
    "_encode_move",
    "_make_ai_engine",
    "launch_gui",
]
